"""Cross-service hash parity for the jobs dedup key.

The fixtures here MUST match what apps/api/internal/domain/job_test.go
produces. If you change the algorithm on either side, regenerate the
expected hashes via:

    go test -run TestComputeDedupKey -v ./internal/domain/...

and update both files in the same commit.
"""

from __future__ import annotations

import json

import pytest

from app.dedup import canonicalise_payload, compute_dedup_key


ORG = "11111111-1111-1111-1111-111111111111"
IMG = "22222222-2222-2222-2222-222222222222"


def test_canonicalise_sorts_keys_recursively() -> None:
    a = canonicalise_payload(json.loads('{"b":2,"a":1,"nested":{"y":2,"x":1}}'))
    b = canonicalise_payload(json.loads('{"nested":{"x":1,"y":2},"a":1,"b":2}'))
    assert a == b


def test_dedup_key_stable_across_key_order() -> None:
    a = canonicalise_payload(json.loads('{"b":2,"a":1,"nested":{"y":2,"x":1}}'))
    b = canonicalise_payload(json.loads('{"nested":{"x":1,"y":2},"a":1,"b":2}'))
    assert compute_dedup_key(ORG, IMG, "auto", a) == compute_dedup_key(ORG, IMG, "auto", b)


def test_dedup_key_changes_on_any_field_change() -> None:
    payload = canonicalise_payload({"k": 1})
    base = compute_dedup_key(ORG, IMG, "auto", payload)

    other_org = "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"
    other_img = "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"
    other_payload = canonicalise_payload({"k": 2})

    assert compute_dedup_key(other_org, IMG, "auto", payload) != base
    assert compute_dedup_key(ORG, other_img, "auto", payload) != base
    assert compute_dedup_key(ORG, IMG, "box", payload) != base
    assert compute_dedup_key(ORG, IMG, "auto", other_payload) != base
    assert compute_dedup_key(ORG, None, "auto", payload) != base


def test_dedup_key_is_hex_sha256() -> None:
    key = compute_dedup_key(ORG, IMG, "auto", canonicalise_payload({}))
    assert len(key) == 64
    int(key, 16)  # raises ValueError if non-hex


def test_floats_rejected() -> None:
    with pytest.raises(TypeError):
        canonicalise_payload({"score": 0.5})


def test_empty_payload_defaults_to_object() -> None:
    assert canonicalise_payload(None) == b"{}"


# Cross-service contract — these literal values MUST match what the Go
# domain.ComputeDedupKey produces for the same input. They are pinned
# here so a change on either side breaks loudly in CI.
def test_cross_service_contract_known_value() -> None:
    payload = canonicalise_payload({"a": 1, "b": [1, 2, 3]})
    key = compute_dedup_key(ORG, IMG, "auto", payload)
    # Generated by running Go:
    #   payload, _ := domain.CanonicalisePayload([]byte(`{"a":1,"b":[1,2,3]}`))
    #   fmt.Println(domain.ComputeDedupKey(orgUUID, &imgUUID, domain.JobTypeAuto, payload))
    expected = "f9b78f4cc6f6355c35da69725d6c38dd707be43343c70151cfb0d9ea4ad14742"
    assert key == expected, f"hash diverged from Go reference: got {key}"
