// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: annotations.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const applyAnnotationPatch = `-- name: ApplyAnnotationPatch :one
UPDATE annotations
SET geometry       = COALESCE($3::jsonb, geometry),
    label_id       = COALESCE($4, label_id),
    human_accepted = COALESCE($5, human_accepted),
    updated_at     = now()
WHERE id = $1 AND org_id = $2 AND deleted_at IS NULL
RETURNING id, org_id, annotation_set_id, label_id, kind, geometry,
          mask_storage_key, ai_score, quality_score, model_used,
          human_accepted, created_by, created_at, updated_at
`

type ApplyAnnotationPatchParams struct {
	ID            uuid.UUID
	OrgID         uuid.UUID
	Column3       []byte
	LabelID       pgtype.UUID
	HumanAccepted *bool
}

type ApplyAnnotationPatchRow struct {
	ID              uuid.UUID
	OrgID           uuid.UUID
	AnnotationSetID uuid.UUID
	LabelID         pgtype.UUID
	Kind            AnnotationKind
	Geometry        []byte
	MaskStorageKey  *string
	AiScore         *float64
	QualityScore    *float64
	ModelUsed       *string
	HumanAccepted   *bool
	CreatedBy       uuid.UUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

// COALESCE-on-NULL pattern: nil pointer from Go arrives as SQL NULL,
// which leaves the column unchanged. Geometry is jsonb so we cast.
func (q *Queries) ApplyAnnotationPatch(ctx context.Context, arg ApplyAnnotationPatchParams) (ApplyAnnotationPatchRow, error) {
	row := q.db.QueryRow(ctx, applyAnnotationPatch,
		arg.ID,
		arg.OrgID,
		arg.Column3,
		arg.LabelID,
		arg.HumanAccepted,
	)
	var i ApplyAnnotationPatchRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.AnnotationSetID,
		&i.LabelID,
		&i.Kind,
		&i.Geometry,
		&i.MaskStorageKey,
		&i.AiScore,
		&i.QualityScore,
		&i.ModelUsed,
		&i.HumanAccepted,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const bumpAnnotationSetVersion = `-- name: BumpAnnotationSetVersion :one
UPDATE annotation_sets
SET version    = version + 1,
    updated_at = now()
WHERE id = $1 AND org_id = $2 AND version = $3
RETURNING version
`

type BumpAnnotationSetVersionParams struct {
	ID      uuid.UUID
	OrgID   uuid.UUID
	Version int64
}

// Returns the new version on success, or no rows on If-Match mismatch.
func (q *Queries) BumpAnnotationSetVersion(ctx context.Context, arg BumpAnnotationSetVersionParams) (int64, error) {
	row := q.db.QueryRow(ctx, bumpAnnotationSetVersion, arg.ID, arg.OrgID, arg.Version)
	var version int64
	err := row.Scan(&version)
	return version, err
}

const getAnnotationSetByImage = `-- name: GetAnnotationSetByImage :one

SELECT id, org_id, image_id, version, notes, created_by, created_at, updated_at
FROM annotation_sets
WHERE image_id = $1 AND org_id = $2
`

type GetAnnotationSetByImageParams struct {
	ImageID uuid.UUID
	OrgID   uuid.UUID
}

// Annotation queries. Optimistic locking lives on annotation_sets.version
// (spec §10). PatchAnnotation runs inside a tx with these three queries
// so the version check + bump + row update are atomic.
func (q *Queries) GetAnnotationSetByImage(ctx context.Context, arg GetAnnotationSetByImageParams) (AnnotationSet, error) {
	row := q.db.QueryRow(ctx, getAnnotationSetByImage, arg.ImageID, arg.OrgID)
	var i AnnotationSet
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ImageID,
		&i.Version,
		&i.Notes,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAnnotationWithSetVersion = `-- name: GetAnnotationWithSetVersion :one
SELECT a.id, a.org_id, a.annotation_set_id, a.label_id, a.kind,
       a.geometry, a.mask_storage_key, a.ai_score, a.quality_score,
       a.model_used, a.human_accepted, a.created_by, a.created_at, a.updated_at,
       s.version AS set_version
FROM annotations a
JOIN annotation_sets s ON s.id = a.annotation_set_id
WHERE a.id = $1 AND a.org_id = $2 AND a.deleted_at IS NULL
`

type GetAnnotationWithSetVersionParams struct {
	ID    uuid.UUID
	OrgID uuid.UUID
}

type GetAnnotationWithSetVersionRow struct {
	ID              uuid.UUID
	OrgID           uuid.UUID
	AnnotationSetID uuid.UUID
	LabelID         pgtype.UUID
	Kind            AnnotationKind
	Geometry        []byte
	MaskStorageKey  *string
	AiScore         *float64
	QualityScore    *float64
	ModelUsed       *string
	HumanAccepted   *bool
	CreatedBy       uuid.UUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
	SetVersion      int64
}

func (q *Queries) GetAnnotationWithSetVersion(ctx context.Context, arg GetAnnotationWithSetVersionParams) (GetAnnotationWithSetVersionRow, error) {
	row := q.db.QueryRow(ctx, getAnnotationWithSetVersion, arg.ID, arg.OrgID)
	var i GetAnnotationWithSetVersionRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.AnnotationSetID,
		&i.LabelID,
		&i.Kind,
		&i.Geometry,
		&i.MaskStorageKey,
		&i.AiScore,
		&i.QualityScore,
		&i.ModelUsed,
		&i.HumanAccepted,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SetVersion,
	)
	return i, err
}

const listAnnotationsBySet = `-- name: ListAnnotationsBySet :many
SELECT id, org_id, annotation_set_id, label_id, kind, geometry,
       mask_storage_key, ai_score, quality_score, model_used,
       human_accepted, created_by, created_at, updated_at
FROM annotations
WHERE annotation_set_id = $1 AND org_id = $2 AND deleted_at IS NULL
ORDER BY created_at ASC
`

type ListAnnotationsBySetParams struct {
	AnnotationSetID uuid.UUID
	OrgID           uuid.UUID
}

type ListAnnotationsBySetRow struct {
	ID              uuid.UUID
	OrgID           uuid.UUID
	AnnotationSetID uuid.UUID
	LabelID         pgtype.UUID
	Kind            AnnotationKind
	Geometry        []byte
	MaskStorageKey  *string
	AiScore         *float64
	QualityScore    *float64
	ModelUsed       *string
	HumanAccepted   *bool
	CreatedBy       uuid.UUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

func (q *Queries) ListAnnotationsBySet(ctx context.Context, arg ListAnnotationsBySetParams) ([]ListAnnotationsBySetRow, error) {
	rows, err := q.db.Query(ctx, listAnnotationsBySet, arg.AnnotationSetID, arg.OrgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAnnotationsBySetRow
	for rows.Next() {
		var i ListAnnotationsBySetRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.AnnotationSetID,
			&i.LabelID,
			&i.Kind,
			&i.Geometry,
			&i.MaskStorageKey,
			&i.AiScore,
			&i.QualityScore,
			&i.ModelUsed,
			&i.HumanAccepted,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const writeAIResult = `-- name: WriteAIResult :exec
UPDATE annotations
SET mask_storage_key = $3,
    ai_score         = $4,
    model_used       = $5,
    updated_at       = now()
WHERE annotation_set_id  = $1
  AND org_id             = $2
  AND deleted_at         IS NULL
  AND human_accepted     IS NULL
`

type WriteAIResultParams struct {
	AnnotationSetID uuid.UUID
	OrgID           uuid.UUID
	MaskStorageKey  *string
	AiScore         *float64
	ModelUsed       *string
}

// Writes AI inference fields onto un-reviewed annotations in a set.
// Skips rows where human_accepted IS NOT NULL so human corrections are
// never overwritten by a later AI inference pass.
func (q *Queries) WriteAIResult(ctx context.Context, arg WriteAIResultParams) error {
	_, err := q.db.Exec(ctx, writeAIResult,
		arg.AnnotationSetID,
		arg.OrgID,
		arg.MaskStorageKey,
		arg.AiScore,
		arg.ModelUsed,
	)
	return err
}
