// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: audit.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const appendAudit = `-- name: AppendAudit :exec
INSERT INTO audit_log (
    org_id, actor_id, actor_kind, action, resource, resource_id,
    metadata, request_id, trace_id
) VALUES ($1, $2, $3, $4, $5, $6, COALESCE($7, '{}'::jsonb), $8, $9)
`

type AppendAuditParams struct {
	OrgID      pgtype.UUID
	ActorID    pgtype.UUID
	ActorKind  string
	Action     string
	Resource   string
	ResourceID pgtype.UUID
	Column7    interface{}
	RequestID  *string
	TraceID    *string
}

func (q *Queries) AppendAudit(ctx context.Context, arg AppendAuditParams) error {
	_, err := q.db.Exec(ctx, appendAudit,
		arg.OrgID,
		arg.ActorID,
		arg.ActorKind,
		arg.Action,
		arg.Resource,
		arg.ResourceID,
		arg.Column7,
		arg.RequestID,
		arg.TraceID,
	)
	return err
}
