// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: images.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const countImages = `-- name: CountImages :one
SELECT COUNT(*)
FROM images
WHERE org_id = $1
  AND deleted_at IS NULL
  AND ($2::image_status IS NULL OR status = $2)
`

type CountImagesParams struct {
	OrgID   uuid.UUID
	Column2 ImageStatus
}

func (q *Queries) CountImages(ctx context.Context, arg CountImagesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countImages, arg.OrgID, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createImage = `-- name: CreateImage :one

INSERT INTO images (
    org_id, uploaded_by, storage_key, content_type, byte_size, status, metadata
) VALUES ($1, $2, $3, $4, $5, 'uploading', COALESCE($6, '{}'::jsonb))
RETURNING id, org_id, uploaded_by, storage_key, storage_etag, content_type, byte_size, width, height, sha256, status, metadata, created_at, updated_at, deleted_at
`

type CreateImageParams struct {
	OrgID       uuid.UUID
	UploadedBy  uuid.UUID
	StorageKey  string
	ContentType string
	ByteSize    int64
	Column6     interface{}
}

// All image queries are tenant-scoped: org_id is the first parameter and
// appears in WHERE on every read/write. See ADR-0002.
func (q *Queries) CreateImage(ctx context.Context, arg CreateImageParams) (Image, error) {
	row := q.db.QueryRow(ctx, createImage,
		arg.OrgID,
		arg.UploadedBy,
		arg.StorageKey,
		arg.ContentType,
		arg.ByteSize,
		arg.Column6,
	)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UploadedBy,
		&i.StorageKey,
		&i.StorageEtag,
		&i.ContentType,
		&i.ByteSize,
		&i.Width,
		&i.Height,
		&i.Sha256,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const finalizeImage = `-- name: FinalizeImage :one
UPDATE images
SET status       = 'ready',
    storage_etag = $3,
    width        = $4,
    height       = $5,
    sha256       = $6,
    updated_at   = now()
WHERE id = $1 AND org_id = $2 AND deleted_at IS NULL
RETURNING id, org_id, uploaded_by, storage_key, storage_etag, content_type, byte_size, width, height, sha256, status, metadata, created_at, updated_at, deleted_at
`

type FinalizeImageParams struct {
	ID          uuid.UUID
	OrgID       uuid.UUID
	StorageEtag *string
	Width       *int32
	Height      *int32
	Sha256      *string
}

func (q *Queries) FinalizeImage(ctx context.Context, arg FinalizeImageParams) (Image, error) {
	row := q.db.QueryRow(ctx, finalizeImage,
		arg.ID,
		arg.OrgID,
		arg.StorageEtag,
		arg.Width,
		arg.Height,
		arg.Sha256,
	)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UploadedBy,
		&i.StorageKey,
		&i.StorageEtag,
		&i.ContentType,
		&i.ByteSize,
		&i.Width,
		&i.Height,
		&i.Sha256,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getImage = `-- name: GetImage :one
SELECT id, org_id, uploaded_by, storage_key, storage_etag, content_type, byte_size, width, height, sha256, status, metadata, created_at, updated_at, deleted_at FROM images
WHERE id = $1 AND org_id = $2 AND deleted_at IS NULL
`

type GetImageParams struct {
	ID    uuid.UUID
	OrgID uuid.UUID
}

func (q *Queries) GetImage(ctx context.Context, arg GetImageParams) (Image, error) {
	row := q.db.QueryRow(ctx, getImage, arg.ID, arg.OrgID)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UploadedBy,
		&i.StorageKey,
		&i.StorageEtag,
		&i.ContentType,
		&i.ByteSize,
		&i.Width,
		&i.Height,
		&i.Sha256,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listImages = `-- name: ListImages :many
SELECT id, org_id, uploaded_by, storage_key, storage_etag, content_type, byte_size, width, height, sha256, status, metadata, created_at, updated_at, deleted_at
FROM images
WHERE org_id = $1
  AND deleted_at IS NULL
  AND ($2::image_status IS NULL OR status = $2)
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListImagesParams struct {
	OrgID   uuid.UUID
	Column2 ImageStatus
	Limit   int32
	Offset  int32
}

func (q *Queries) ListImages(ctx context.Context, arg ListImagesParams) ([]Image, error) {
	rows, err := q.db.Query(ctx, listImages,
		arg.OrgID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Image
	for rows.Next() {
		var i Image
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.UploadedBy,
			&i.StorageKey,
			&i.StorageEtag,
			&i.ContentType,
			&i.ByteSize,
			&i.Width,
			&i.Height,
			&i.Sha256,
			&i.Status,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteImage = `-- name: SoftDeleteImage :exec
UPDATE images SET deleted_at = now()
WHERE id = $1 AND org_id = $2 AND deleted_at IS NULL
`

type SoftDeleteImageParams struct {
	ID    uuid.UUID
	OrgID uuid.UUID
}

func (q *Queries) SoftDeleteImage(ctx context.Context, arg SoftDeleteImageParams) error {
	_, err := q.db.Exec(ctx, softDeleteImage, arg.ID, arg.OrgID)
	return err
}
