// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: jobs.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const applyJobCallback = `-- name: ApplyJobCallback :one
UPDATE jobs
SET state       = $1::job_state,
    attempt     = $2,
    error       = $3,
    result      = $4::jsonb,
    started_at  = COALESCE(started_at, CASE WHEN $1::job_state = 'running' THEN now() ELSE NULL END),
    finished_at = CASE WHEN $1::job_state IN ('succeeded', 'failed', 'cancelled') THEN now() ELSE finished_at END,
    updated_at  = now()
WHERE id = $5
  AND state NOT IN ('succeeded', 'failed', 'cancelled')
RETURNING id, org_id, image_id, submitted_by, type, state, payload,
          dedup_key, attempt, error, result, started_at, finished_at,
          created_at, updated_at
`

type ApplyJobCallbackParams struct {
	State   JobState
	Attempt int16
	Error   *string
	Result  []byte
	ID      uuid.UUID
}

// Worker callback: identified by job id only (the endpoint is HMAC-
// authenticated; the org is read out of the existing row via RETURNING
// and used for downstream audit/SSE fan-out). Idempotent guard: refuse
// to overwrite an already-terminal state.
//
// Note on $2::job_state casts: without explicit casts at every reference,
// Postgres deduces $2 as job_state from `state = $2` and as text from
// the CASE comparisons against literals, then errors with "inconsistent
// types deduced for parameter $2" (SQLSTATE 42P08). Casting at every
// reference forces a single inferred type for the parameter and lets
// Postgres compare enum values to literals via implicit upcast.
func (q *Queries) ApplyJobCallback(ctx context.Context, arg ApplyJobCallbackParams) (Job, error) {
	row := q.db.QueryRow(ctx, applyJobCallback,
		arg.State,
		arg.Attempt,
		arg.Error,
		arg.Result,
		arg.ID,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ImageID,
		&i.SubmittedBy,
		&i.Type,
		&i.State,
		&i.Payload,
		&i.DedupKey,
		&i.Attempt,
		&i.Error,
		&i.Result,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createJob = `-- name: CreateJob :one

INSERT INTO jobs (
    id, org_id, image_id, submitted_by, type, state, payload, dedup_key, attempt
) VALUES (
    $1, $2, $3, $4, $5, $6, $7::jsonb, $8, $9
)
RETURNING id, org_id, image_id, submitted_by, type, state, payload,
          dedup_key, attempt, error, result, started_at, finished_at,
          created_at, updated_at
`

type CreateJobParams struct {
	ID          uuid.UUID
	OrgID       uuid.UUID
	ImageID     pgtype.UUID
	SubmittedBy uuid.UUID
	Type        JobType
	State       JobState
	Column7     []byte
	DedupKey    string
	Attempt     int16
}

// All job queries are tenant-scoped (org_id appears in every WHERE).
// The 10-minute dedup window from spec §11 is applied as a `created_at`
// predicate parameterised by the caller, not hard-coded here, so the
// use-case owns the policy.
func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, createJob,
		arg.ID,
		arg.OrgID,
		arg.ImageID,
		arg.SubmittedBy,
		arg.Type,
		arg.State,
		arg.Column7,
		arg.DedupKey,
		arg.Attempt,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ImageID,
		&i.SubmittedBy,
		&i.Type,
		&i.State,
		&i.Payload,
		&i.DedupKey,
		&i.Attempt,
		&i.Error,
		&i.Result,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findActiveJobByDedupKey = `-- name: FindActiveJobByDedupKey :one
SELECT id, org_id, image_id, submitted_by, type, state, payload,
       dedup_key, attempt, error, result, started_at, finished_at,
       created_at, updated_at
FROM jobs
WHERE org_id = $1
  AND dedup_key = $2
  AND state IN ('pending', 'running', 'succeeded')
  AND created_at >= $3
ORDER BY created_at DESC
LIMIT 1
`

type FindActiveJobByDedupKeyParams struct {
	OrgID     uuid.UUID
	DedupKey  string
	CreatedAt time.Time
}

func (q *Queries) FindActiveJobByDedupKey(ctx context.Context, arg FindActiveJobByDedupKeyParams) (Job, error) {
	row := q.db.QueryRow(ctx, findActiveJobByDedupKey, arg.OrgID, arg.DedupKey, arg.CreatedAt)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ImageID,
		&i.SubmittedBy,
		&i.Type,
		&i.State,
		&i.Payload,
		&i.DedupKey,
		&i.Attempt,
		&i.Error,
		&i.Result,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJob = `-- name: GetJob :one
SELECT id, org_id, image_id, submitted_by, type, state, payload,
       dedup_key, attempt, error, result, started_at, finished_at,
       created_at, updated_at
FROM jobs
WHERE id = $1 AND org_id = $2
`

type GetJobParams struct {
	ID    uuid.UUID
	OrgID uuid.UUID
}

func (q *Queries) GetJob(ctx context.Context, arg GetJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, getJob, arg.ID, arg.OrgID)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ImageID,
		&i.SubmittedBy,
		&i.Type,
		&i.State,
		&i.Payload,
		&i.DedupKey,
		&i.Attempt,
		&i.Error,
		&i.Result,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJobByID = `-- name: GetJobByID :one

SELECT id, org_id, image_id, submitted_by, type, state, payload,
       dedup_key, attempt, error, result, started_at, finished_at,
       created_at, updated_at
FROM jobs
WHERE id = $1
`

// (jobs queries continue below — annotation queries live in annotations.sql)
// Worker-side helper for the callback handler — same as GetJob but
// without the org_id filter (HMAC has already authenticated). External
// handlers MUST keep using GetJob so cross-tenant reads stay 404.
func (q *Queries) GetJobByID(ctx context.Context, id uuid.UUID) (Job, error) {
	row := q.db.QueryRow(ctx, getJobByID, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ImageID,
		&i.SubmittedBy,
		&i.Type,
		&i.State,
		&i.Payload,
		&i.DedupKey,
		&i.Attempt,
		&i.Error,
		&i.Result,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markJobErrored = `-- name: MarkJobErrored :exec
UPDATE jobs
SET state       = 'failed',
    error       = $3,
    finished_at = now(),
    updated_at  = now()
WHERE id = $1 AND org_id = $2
`

type MarkJobErroredParams struct {
	ID    uuid.UUID
	OrgID uuid.UUID
	Error *string
}

func (q *Queries) MarkJobErrored(ctx context.Context, arg MarkJobErroredParams) error {
	_, err := q.db.Exec(ctx, markJobErrored, arg.ID, arg.OrgID, arg.Error)
	return err
}
