// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: labels.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const listLabelsByOrg = `-- name: ListLabelsByOrg :many

SELECT id, org_id, name, color, description, archived, created_at
FROM labels
WHERE org_id = $1 AND archived = FALSE
ORDER BY name ASC
`

// Label catalog (spec §10 — picker source). Per-org, soft-archive via
// the `archived` boolean. The studio reads this list to populate its
// label dropdown; bootstrap data is currently inserted via SQL until a
// CRUD admin surface lands.
// Returns all non-archived labels for an org, alphabetised by name so
// the picker has a stable order. ID, name, color are everything the
// studio renders today; description ships for future tooltips.
func (q *Queries) ListLabelsByOrg(ctx context.Context, orgID uuid.UUID) ([]Label, error) {
	rows, err := q.db.Query(ctx, listLabelsByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Label
	for rows.Next() {
		var i Label
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Color,
			&i.Description,
			&i.Archived,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
