// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: memberships.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createMembership = `-- name: CreateMembership :one
INSERT INTO memberships (org_id, user_id, role, invited_by)
VALUES ($1, $2, $3, $4)
RETURNING id, org_id, user_id, role, invited_by, created_at
`

type CreateMembershipParams struct {
	OrgID     uuid.UUID
	UserID    uuid.UUID
	Role      MembershipRole
	InvitedBy pgtype.UUID
}

func (q *Queries) CreateMembership(ctx context.Context, arg CreateMembershipParams) (Membership, error) {
	row := q.db.QueryRow(ctx, createMembership,
		arg.OrgID,
		arg.UserID,
		arg.Role,
		arg.InvitedBy,
	)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UserID,
		&i.Role,
		&i.InvitedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMembership = `-- name: DeleteMembership :exec
DELETE FROM memberships
WHERE org_id = $1 AND user_id = $2
`

type DeleteMembershipParams struct {
	OrgID  uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteMembership(ctx context.Context, arg DeleteMembershipParams) error {
	_, err := q.db.Exec(ctx, deleteMembership, arg.OrgID, arg.UserID)
	return err
}

const getMembership = `-- name: GetMembership :one
SELECT id, org_id, user_id, role, invited_by, created_at FROM memberships
WHERE org_id = $1 AND user_id = $2
`

type GetMembershipParams struct {
	OrgID  uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetMembership(ctx context.Context, arg GetMembershipParams) (Membership, error) {
	row := q.db.QueryRow(ctx, getMembership, arg.OrgID, arg.UserID)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UserID,
		&i.Role,
		&i.InvitedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listMembershipsForUser = `-- name: ListMembershipsForUser :many
SELECT m.id, m.org_id, m.user_id, m.role, m.invited_by, m.created_at, o.slug AS org_slug, o.name AS org_name
FROM memberships m
JOIN organizations o ON o.id = m.org_id
WHERE m.user_id = $1 AND o.deleted_at IS NULL
ORDER BY m.created_at ASC
`

type ListMembershipsForUserRow struct {
	ID        uuid.UUID
	OrgID     uuid.UUID
	UserID    uuid.UUID
	Role      MembershipRole
	InvitedBy pgtype.UUID
	CreatedAt time.Time
	OrgSlug   string
	OrgName   string
}

func (q *Queries) ListMembershipsForUser(ctx context.Context, userID uuid.UUID) ([]ListMembershipsForUserRow, error) {
	rows, err := q.db.Query(ctx, listMembershipsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMembershipsForUserRow
	for rows.Next() {
		var i ListMembershipsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.UserID,
			&i.Role,
			&i.InvitedBy,
			&i.CreatedAt,
			&i.OrgSlug,
			&i.OrgName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMembershipRole = `-- name: UpdateMembershipRole :one
UPDATE memberships SET role = $3
WHERE org_id = $1 AND user_id = $2
RETURNING id, org_id, user_id, role, invited_by, created_at
`

type UpdateMembershipRoleParams struct {
	OrgID  uuid.UUID
	UserID uuid.UUID
	Role   MembershipRole
}

func (q *Queries) UpdateMembershipRole(ctx context.Context, arg UpdateMembershipRoleParams) (Membership, error) {
	row := q.db.QueryRow(ctx, updateMembershipRole, arg.OrgID, arg.UserID, arg.Role)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UserID,
		&i.Role,
		&i.InvitedBy,
		&i.CreatedAt,
	)
	return i, err
}
