// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AnnotationKind string

const (
	AnnotationKindBbox    AnnotationKind = "bbox"
	AnnotationKindPolygon AnnotationKind = "polygon"
	AnnotationKindMask    AnnotationKind = "mask"
	AnnotationKindPoint   AnnotationKind = "point"
)

func (e *AnnotationKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AnnotationKind(s)
	case string:
		*e = AnnotationKind(s)
	default:
		return fmt.Errorf("unsupported scan type for AnnotationKind: %T", src)
	}
	return nil
}

type NullAnnotationKind struct {
	AnnotationKind AnnotationKind
	Valid          bool // Valid is true if AnnotationKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAnnotationKind) Scan(value interface{}) error {
	if value == nil {
		ns.AnnotationKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AnnotationKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAnnotationKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AnnotationKind), nil
}

type ImageStatus string

const (
	ImageStatusUploading ImageStatus = "uploading"
	ImageStatusReady     ImageStatus = "ready"
	ImageStatusErrored   ImageStatus = "errored"
	ImageStatusArchived  ImageStatus = "archived"
)

func (e *ImageStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ImageStatus(s)
	case string:
		*e = ImageStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ImageStatus: %T", src)
	}
	return nil
}

type NullImageStatus struct {
	ImageStatus ImageStatus
	Valid       bool // Valid is true if ImageStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullImageStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ImageStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ImageStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullImageStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ImageStatus), nil
}

type JobState string

const (
	JobStatePending   JobState = "pending"
	JobStateRunning   JobState = "running"
	JobStateSucceeded JobState = "succeeded"
	JobStateFailed    JobState = "failed"
	JobStateCancelled JobState = "cancelled"
)

func (e *JobState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = JobState(s)
	case string:
		*e = JobState(s)
	default:
		return fmt.Errorf("unsupported scan type for JobState: %T", src)
	}
	return nil
}

type NullJobState struct {
	JobState JobState
	Valid    bool // Valid is true if JobState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullJobState) Scan(value interface{}) error {
	if value == nil {
		ns.JobState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.JobState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullJobState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.JobState), nil
}

type JobType string

const (
	JobTypeAuto    JobType = "auto"
	JobTypeBox     JobType = "box"
	JobTypePoints  JobType = "points"
	JobTypePolygon JobType = "polygon"
	JobTypeDetect  JobType = "detect"
	JobTypeTrain   JobType = "train"
	JobTypeExport  JobType = "export"
)

func (e *JobType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = JobType(s)
	case string:
		*e = JobType(s)
	default:
		return fmt.Errorf("unsupported scan type for JobType: %T", src)
	}
	return nil
}

type NullJobType struct {
	JobType JobType
	Valid   bool // Valid is true if JobType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullJobType) Scan(value interface{}) error {
	if value == nil {
		ns.JobType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.JobType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullJobType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.JobType), nil
}

type MembershipRole string

const (
	MembershipRoleOwner     MembershipRole = "owner"
	MembershipRoleAdmin     MembershipRole = "admin"
	MembershipRoleAnnotator MembershipRole = "annotator"
	MembershipRoleViewer    MembershipRole = "viewer"
)

func (e *MembershipRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MembershipRole(s)
	case string:
		*e = MembershipRole(s)
	default:
		return fmt.Errorf("unsupported scan type for MembershipRole: %T", src)
	}
	return nil
}

type NullMembershipRole struct {
	MembershipRole MembershipRole
	Valid          bool // Valid is true if MembershipRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMembershipRole) Scan(value interface{}) error {
	if value == nil {
		ns.MembershipRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MembershipRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMembershipRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MembershipRole), nil
}

type Annotation struct {
	ID              uuid.UUID
	OrgID           uuid.UUID
	AnnotationSetID uuid.UUID
	LabelID         pgtype.UUID
	Kind            AnnotationKind
	Geometry        []byte
	MaskStorageKey  *string
	AiScore         *float64
	QualityScore    *float64
	ModelUsed       *string
	HumanAccepted   *bool
	CreatedBy       uuid.UUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
	DeletedAt       pgtype.Timestamptz
}

type AnnotationSet struct {
	ID        uuid.UUID
	OrgID     uuid.UUID
	ImageID   uuid.UUID
	Version   int64
	Notes     *string
	CreatedBy uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

type ApiKey struct {
	ID         uuid.UUID
	OrgID      uuid.UUID
	CreatedBy  uuid.UUID
	Name       string
	KeyHash    string
	KeySuffix  string
	Scopes     []string
	LastUsedAt pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
	CreatedAt  time.Time
}

type AuditLog struct {
	ID         int64
	OccurredAt time.Time
	OrgID      pgtype.UUID
	ActorID    pgtype.UUID
	ActorKind  string
	Action     string
	Resource   string
	ResourceID pgtype.UUID
	Metadata   []byte
	RequestID  *string
	TraceID    *string
}

type BetterAuthAccount struct {
	ID                    string
	UserID                uuid.UUID
	AccountID             string
	ProviderID            string
	AccessToken           *string
	RefreshToken          *string
	IDToken               *string
	AccessTokenExpiresAt  pgtype.Timestamptz
	RefreshTokenExpiresAt pgtype.Timestamptz
	Scope                 *string
	Password              *string
	CreatedAt             time.Time
	UpdatedAt             time.Time
}

type BetterAuthSession struct {
	ID        string
	UserID    uuid.UUID
	Token     string
	IpAddress *string
	UserAgent *string
	ExpiresAt time.Time
	CreatedAt time.Time
	UpdatedAt time.Time
}

type BetterAuthVerification struct {
	ID         string
	Identifier string
	Value      string
	ExpiresAt  time.Time
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type DatasetSnapshot struct {
	ID         uuid.UUID
	OrgID      uuid.UUID
	Semver     string
	StorageKey string
	Format     string
	ImageCount int32
	LabelCount int32
	CreatedBy  uuid.UUID
	CreatedAt  time.Time
}

type Image struct {
	ID          uuid.UUID
	OrgID       uuid.UUID
	UploadedBy  uuid.UUID
	StorageKey  string
	StorageEtag *string
	ContentType string
	ByteSize    int64
	Width       *int32
	Height      *int32
	Sha256      *string
	Status      ImageStatus
	Metadata    []byte
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   pgtype.Timestamptz
}

type Job struct {
	ID          uuid.UUID
	OrgID       uuid.UUID
	ImageID     pgtype.UUID
	SubmittedBy uuid.UUID
	Type        JobType
	State       JobState
	Payload     []byte
	DedupKey    string
	Attempt     int16
	Error       *string
	Result      []byte
	StartedAt   pgtype.Timestamptz
	FinishedAt  pgtype.Timestamptz
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Label struct {
	ID          uuid.UUID
	OrgID       uuid.UUID
	Name        string
	Color       string
	Description *string
	Archived    bool
	CreatedAt   time.Time
}

type Membership struct {
	ID        uuid.UUID
	OrgID     uuid.UUID
	UserID    uuid.UUID
	Role      MembershipRole
	InvitedBy pgtype.UUID
	CreatedAt time.Time
}

type ModelVersion struct {
	ID           uuid.UUID
	OrgID        pgtype.UUID
	Family       string
	Semver       string
	OnnxKey      *string
	WeightsKey   *string
	MeanIou      *float64
	Map50        *float64
	EmbeddingDim *int32
	IsActive     bool
	PromotedAt   pgtype.Timestamptz
	CreatedAt    time.Time
}

type Organization struct {
	ID            uuid.UUID
	Slug          string
	Name          string
	Plan          string
	CorsAllowlist []string
	Settings      []byte
	CreatedAt     time.Time
	UpdatedAt     time.Time
	DeletedAt     pgtype.Timestamptz
}

type User struct {
	ID            uuid.UUID
	Email         string
	EmailVerified bool
	DisplayName   *string
	AvatarUrl     *string
	Locale        string
	CreatedAt     time.Time
	UpdatedAt     time.Time
	DeletedAt     pgtype.Timestamptz
}
