// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AppendAudit(ctx context.Context, arg AppendAuditParams) error
	// COALESCE-on-NULL pattern: nil pointer from Go arrives as SQL NULL,
	// which leaves the column unchanged. Geometry is jsonb so we cast.
	ApplyAnnotationPatch(ctx context.Context, arg ApplyAnnotationPatchParams) (ApplyAnnotationPatchRow, error)
	// Worker callback: identified by job id only (the endpoint is HMAC-
	// authenticated; the org is read out of the existing row via RETURNING
	// and used for downstream audit/SSE fan-out). Idempotent guard: refuse
	// to overwrite an already-terminal state.
	//
	// Note on $2::job_state casts: without explicit casts at every reference,
	// Postgres deduces $2 as job_state from `state = $2` and as text from
	// the CASE comparisons against literals, then errors with "inconsistent
	// types deduced for parameter $2" (SQLSTATE 42P08). Casting at every
	// reference forces a single inferred type for the parameter and lets
	// Postgres compare enum values to literals via implicit upcast.
	ApplyJobCallback(ctx context.Context, arg ApplyJobCallbackParams) (Job, error)
	// Returns the new version on success, or no rows on If-Match mismatch.
	BumpAnnotationSetVersion(ctx context.Context, arg BumpAnnotationSetVersionParams) (int64, error)
	CountImages(ctx context.Context, arg CountImagesParams) (int64, error)
	// All image queries are tenant-scoped: org_id is the first parameter and
	// appears in WHERE on every read/write. See ADR-0002.
	CreateImage(ctx context.Context, arg CreateImageParams) (Image, error)
	// All job queries are tenant-scoped (org_id appears in every WHERE).
	// The 10-minute dedup window from spec §11 is applied as a `created_at`
	// predicate parameterised by the caller, not hard-coded here, so the
	// use-case owns the policy.
	CreateJob(ctx context.Context, arg CreateJobParams) (Job, error)
	CreateMembership(ctx context.Context, arg CreateMembershipParams) (Membership, error)
	CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteExpiredSessions(ctx context.Context) error
	DeleteMembership(ctx context.Context, arg DeleteMembershipParams) error
	FinalizeImage(ctx context.Context, arg FinalizeImageParams) (Image, error)
	FindActiveJobByDedupKey(ctx context.Context, arg FindActiveJobByDedupKeyParams) (Job, error)
	// Annotation queries. Optimistic locking lives on annotation_sets.version
	// (spec §10). PatchAnnotation runs inside a tx with these three queries
	// so the version check + bump + row update are atomic.
	GetAnnotationSetByImage(ctx context.Context, arg GetAnnotationSetByImageParams) (AnnotationSet, error)
	GetAnnotationWithSetVersion(ctx context.Context, arg GetAnnotationWithSetVersionParams) (GetAnnotationWithSetVersionRow, error)
	GetImage(ctx context.Context, arg GetImageParams) (Image, error)
	GetJob(ctx context.Context, arg GetJobParams) (Job, error)
	// (jobs queries continue below — annotation queries live in annotations.sql)
	// Worker-side helper for the callback handler — same as GetJob but
	// without the org_id filter (HMAC has already authenticated). External
	// handlers MUST keep using GetJob so cross-tenant reads stay 404.
	GetJobByID(ctx context.Context, id uuid.UUID) (Job, error)
	GetMembership(ctx context.Context, arg GetMembershipParams) (Membership, error)
	GetOrganizationByID(ctx context.Context, id uuid.UUID) (Organization, error)
	GetOrganizationBySlug(ctx context.Context, slug string) (Organization, error)
	// Better Auth populates this; the API reads it to authenticate requests.
	GetSessionByToken(ctx context.Context, token string) (GetSessionByTokenRow, error)
	GetUserByEmail(ctx context.Context, lower string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	ListAnnotationsBySet(ctx context.Context, arg ListAnnotationsBySetParams) ([]ListAnnotationsBySetRow, error)
	ListImages(ctx context.Context, arg ListImagesParams) ([]Image, error)
	ListMembershipsForUser(ctx context.Context, userID uuid.UUID) ([]ListMembershipsForUserRow, error)
	ListOrganizationsForUser(ctx context.Context, userID uuid.UUID) ([]Organization, error)
	MarkJobErrored(ctx context.Context, arg MarkJobErroredParams) error
	SoftDeleteImage(ctx context.Context, arg SoftDeleteImageParams) error
	SoftDeleteUser(ctx context.Context, id uuid.UUID) error
	UpdateMembershipRole(ctx context.Context, arg UpdateMembershipRoleParams) (Membership, error)
}

var _ Querier = (*Queries)(nil)
